AWSTemplateFormatVersion: "2010-09-09"
Resources:
  # CloudFront Origin Access Identity (OAI)
  FrontendOAI:
    Type: AWS::CloudFront::CloudFrontOriginAccessIdentity
    Properties:
      CloudFrontOriginAccessIdentityConfig:
        Comment: "OAI for accessing S3 frontend bucket"

  # CloudFront Distribution
  CloudFrontDistribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Origins:
          - DomainName: !ImportValue FrontendS3BucketDomainName
            Id: "FrontendS3Origin"
            S3OriginConfig:
              OriginAccessIdentity: !Sub "origin-access-identity/cloudfront/${FrontendOAI}"
        Enabled: true
        DefaultCacheBehavior:
          TargetOriginId: "FrontendS3Origin"
          ViewerProtocolPolicy: "redirect-to-https"
          ForwardedValues:
            QueryString: "false"
            Cookies:
              Forward: "none"

        PriceClass: "PriceClass_100"
        DefaultRootObject: "index.html"
        # Custom Error Responses to support SPA
        CustomErrorResponses:
          - ErrorCode: 403
            ResponseCode: 200
            ErrorCachingMinTTL: 300
            ResponsePagePath: "/index.html"

  # S3 Bucket Policy for Frontend Artifacts to allow CloudFront OAI to access the bucket
  FrontendS3BucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !ImportValue FrontendS3BucketName
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Sid: "AllowCloudFrontAccess"
            Effect: "Allow"
            Principal:
              AWS: !Sub "arn:aws:iam::cloudfront:user/CloudFront Origin Access Identity ${FrontendOAI}"
            Action: "s3:GetObject"
            Resource: !ImportValue FrontendS3BucketARN

Outputs:
  CloudFrontDistributionId:
    Description: "The ID of the CloudFront distribution"
    Value: !Ref CloudFrontDistribution

  CloudFrontDistributionDomainName:
    Description: "The domain name of the CloudFront distribution"
    Value: !GetAtt CloudFrontDistribution.DomainName
