AWSTemplateFormatVersion: "2010-09-09"
Parameters:
  GitHubConnectionArn:
    Type: String

  GitHubUser:
    Type: String

  GitHubRepo:
    Type: String

  # Github repo branch
  GitHubBranch:
    Type: String
    Default: main

Resources:
  CodePipeline:
    Type: AWS::CodePipeline::Pipeline
    DependsOn:
      - CodeDeployApp
      - CodeDeployDeploymentGroup
      - BackendCodeBuildProject
      - FrontendCodeBuildProject
    Properties:
      RoleArn: !ImportValue CodePipelineServiceRoleArn
      ArtifactStore:
        Type: S3
        Location: !ImportValue CodePipelineArtifactsBucketName
      Stages:
        - Name: Source
          Actions:
            - Name: GitHubSource
              ActionTypeId:
                Category: Source
                Owner: AWS
                Provider: CodeStarSourceConnection
                Version: "1"
              OutputArtifacts:
                - Name: SourceOutput
              Configuration:
                ConnectionArn: !Ref GitHubConnectionArn
                FullRepositoryId: !Sub ${GitHubUser}/${GitHubRepo}
                BranchName: !Ref GitHubBranch

        - Name: Build
          Actions:
            - Name: BackendBuild
              ActionTypeId:
                Category: Build
                Owner: AWS
                Provider: CodeBuild
                Version: "1"
              InputArtifacts:
                - Name: SourceOutput
              OutputArtifacts:
                - Name: BackendBuildOutput
              Configuration:
                ProjectName: !Ref BackendCodeBuildProject
            - Name: FrontendBuild
              ActionTypeId:
                Category: Build
                Owner: AWS
                Provider: CodeBuild
                Version: "1"
              InputArtifacts:
                - Name: SourceOutput
              OutputArtifacts:
                - Name: FrontendBuildOutput
              Configuration:
                ProjectName: !Ref FrontendCodeBuildProject

        - Name: Deploy
          Actions:
            - Name: DeployBackend
              ActionTypeId:
                Category: Deploy
                Owner: AWS
                Provider: CodeDeploy
                Version: "1"
              InputArtifacts:
                - Name: BackendBuildOutput
              Configuration:
                ApplicationName: !Ref CodeDeployApp
                DeploymentGroupName: !Ref CodeDeployDeploymentGroup
            - Name: DeployFrontend
              ActionTypeId:
                Category: Deploy
                Owner: AWS
                Provider: S3
                Version: "1"
              InputArtifacts:
                - Name: FrontendBuildOutput
              Configuration:
                BucketName: !ImportValue FrontendS3BucketName
                Extract: true

  # CodeDeploy
  CodeDeployApp:
    Type: AWS::CodeDeploy::Application
    Properties:
      ComputePlatform: Server

  # CodeDeploy DeploymentGroup
  CodeDeployDeploymentGroup:
    Type: AWS::CodeDeploy::DeploymentGroup
    Properties:
      ApplicationName: !Ref CodeDeployApp
      DeploymentGroupName: "BackendDeploymentGroup"
      ServiceRoleArn: !ImportValue CodeDeployServiceRoleArn
      DeploymentConfigName: "CodeDeployDefault.AllAtOnce"
      Ec2TagFilters:
        - Key: "Name"
          Value: !ImportValue EC2InstanceName
          Type: "KEY_AND_VALUE"

  # Backend CodeBuild
  BackendCodeBuildProject:
    Type: AWS::CodeBuild::Project
    Properties:
      Name: "BackendCodeBuild"
      ServiceRole: !ImportValue CodeBuildServiceRoleArn
      Source:
        Type: CODEPIPELINE
        BuildSpec: buildspec.yml
      Artifacts:
        Type: CODEPIPELINE
      Environment:
        ComputeType: "BUILD_GENERAL1_SMALL"
        Image: "aws/codebuild/standard:5.0"
        Type: "LINUX_CONTAINER"

  # Frontend CodeBuild
  FrontendCodeBuildProject:
    Type: AWS::CodeBuild::Project
    Properties:
      Name: "FrontendCodeBuild"
      ServiceRole: !ImportValue CodeBuildServiceRoleArn
      Source:
        Type: CODEPIPELINE
        BuildSpec: buildspec-frontend.yml
      Artifacts:
        Type: CODEPIPELINE
      Environment:
        ComputeType: "BUILD_GENERAL1_SMALL"
        Image: "aws/codebuild/standard:5.0"
        Type: "LINUX_CONTAINER"
        EnvironmentVariables:
          - Name: VITE_API_URL
            Value: !ImportValue EC2InstancePublicAPI
            Type: PLAINTEXT
