AWSTemplateFormatVersion: "2010-09-09"
Parameters:
  KeyPairName:
    Type: String
    Description: The name of an existing Amazon EC2 key pair in this region to use to SSH into the Amazon EC2 instances.
    Default: EC2Tutorial

  EC2InstanceName:
    Type: String
    Description: The name of the EC2 instance
    Default: EC2InstanceDemo

  WebServerPort:
    Type: Number

Resources:
  EC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.micro
      ImageId: "ami-08970251d20e940b0" # Amazon Linux 2023 AMI
      KeyName: !Ref KeyPairName
      VpcId: !ImportValue VpcId
      SubnetId: !ImportValue PublicSubnetAId
      SecurityGroupIds:
        - !ImportValue EC2SecurityGroupId
      IamInstanceProfile: !ImportValue EC2InstanceProfileName
      UserData: !Base64 |
        #!/bin/bash
        # Update system packages
        dnf update -y

        # Install dependencies
        dnf install -y ruby wget

        # Download CodeDeploy Agent
        cd /home/ec2-user
        wget https://aws-codedeploy-us-east-2.s3.us-east-2.amazonaws.com/latest/install

        # Set execute permissions on the install file
        chmod +x ./install
        sudo ./install auto

        # Start and enable the CodeDeploy agent service
        systemctl start codedeploy-agent
        systemctl enable codedeploy-agent

        # Check the status of the CodeDeploy agent
        systemctl status codedeploy-agent
      Tags:
        - Key: Name
          Value: !Ref EC2InstanceName

Outputs:
  EC2InstanceId:
    Value: !Ref EC2Instance
    Export:
      Name: EC2InstanceId

  EC2InstancePublicDNS:
    Description: "Public DNS of EC2 instance"
    Value: !GetAtt EC2Instance.PublicDnsName
    Export:
      Name: EC2InstancePublicDNS

  EC2InstancePublicAPI:
    Description: "EC2 instance Public API"
    Value: !Sub "http://${EC2Instance.PublicDnsName}:${WebServerPort}/api"
    Export:
      Name: EC2InstancePublicAPI

  EC2InstanceName:
    Value: !Ref EC2InstanceName
    Export:
      Name: EC2InstanceName
