AWSTemplateFormatVersion: "2010-09-09"
Parameters:
  GitHubConnectionArn:
    Type: String
    Description: "The ARN of the GitHub connection in AWS CodeStar Connections"

  MyIpAddress:
    Type: String
    Description: "Your IP address for SSH access, e.g., 203.0.113.0/32"

  RDSMasterUsername:
    Type: String
    Description: "The master username for your RDS instance (e.g., dbadmin)"
    Default: dbadmin

  WebServerPort:
    Type: Number
    Description: "Port for the web server (e.g., 3000)"
    Default: 3000

Resources:
  # S3 Buckets Stack
  S3BucketsStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: "https://s3.amazonaws.com/node-react-infrastructure-bucket/s3-buckets.yml"

  # IAM Roles Stack
  IAMRolesStack:
    Type: AWS::CloudFormation::Stack
    DependsOn: S3BucketsStack
    Properties:
      TemplateURL: "https://s3.amazonaws.com/node-react-infrastructure-bucket/iam-roles.yml"
      Parameters:
        GitHubConnectionArn: !Ref GitHubConnectionArn

  # Network Stack
  NetworkStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: "https://s3.amazonaws.com/node-react-infrastructure-bucket/network.yml"
      Parameters:
        MyIpAddress: !Ref MyIpAddress
        WebServerPort: !Ref WebServerPort

  # EC2 Instance Stack
  EC2InstanceStack:
    Type: AWS::CloudFormation::Stack
    DependsOn:
      - NetworkStack
      - IAMRolesStack
    Properties:
      TemplateURL: "https://s3.amazonaws.com/node-react-infrastructure-bucket/ec2-instance.yml"
      Parameters:
        WebServerPort: !Ref WebServerPort

  # RDS Instance Stack
  RDSInstanceStack:
    Type: AWS::CloudFormation::Stack
    DependsOn: NetworkStack
    Properties:
      TemplateURL: "https://s3.amazonaws.com/node-react-infrastructure-bucket/rds-instance.yml"
      Parameters:
        RDSMasterUsername: !Ref RDSMasterUsername

  # SSM Stack
  SSMStack:
    Type: AWS::CloudFormation::Stack
    DependsOn: RDSInstanceStack
    Properties:
      TemplateURL: "https://s3.amazonaws.com/node-react-infrastructure-bucket/ssm.yml"

  # CloudFront Stack
  CloudFrontStack:
    Type: AWS::CloudFormation::Stack
    DependsOn: S3BucketsStack
    Properties:
      TemplateURL: "https://s3.amazonaws.com/node-react-infrastructure-bucket/cloudfront.yml"

  # CodePipeline Stack
  CodePipelineStack:
    Type: AWS::CloudFormation::Stack
    DependsOn:
      - S3BucketsStack
      - IAMRolesStack
      - EC2InstanceStack
    Properties:
      TemplateURL: "https://s3.amazonaws.com/node-react-infrastructure-bucket/codepipeline.yml"
      Parameters:
        GitHubConnectionArn: !Ref GitHubConnectionArn
