AWSTemplateFormatVersion: "2010-09-09"
Resources:
  # CodePipeline Artifacts S3 bucket
  CodePipelineArtifactsBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: "codepipeline-artifacts-demo-bucket"

  # Frontend Artifacts S3 bucket
  FrontendS3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: "frontend-deployment-demo-bucket"

Outputs:
  CodePipelineArtifactsBucketName:
    Description: "The name of the CodePipeline Artifacts S3 bucket"
    Value: !Ref CodePipelineArtifactsBucket
    Export:
      Name: CodePipelineArtifactsBucketName

  CodePipelineArtifactsBucketARN:
    Description: "The ARN of the CodePipeline Artifacts S3 bucket"
    Value: !Sub "arn:aws:s3:::${CodePipelineArtifactsBucket}/*"
    Export:
      Name: CodePipelineArtifactsBucketARN

  FrontendS3BucketName:
    Description: "The name of the Frontend Artifacts S3 bucket"
    Value: !Ref FrontendS3Bucket
    Export:
      Name: FrontendS3BucketName

  FrontendS3BucketARN:
    Description: "The ARN of the Frontend Artifacts S3 bucket"
    Value: !Sub "arn:aws:s3:::${FrontendS3Bucket}/*"
    Export:
      Name: FrontendS3BucketARN

  FrontendS3BucketDomainName:
    Description: "Domain name of the S3 bucket"
    Value: !Sub "${FrontendS3Bucket}.s3.${AWS::Region}.amazonaws.com"
    Export:
      Name: FrontendS3BucketDomainName
