AWSTemplateFormatVersion: "2010-09-09"
Parameters:
  ProjectName:
    Type: String

Resources:
  # SSM Parameter Store for DB Host (RDS endpoint)
  DBHostParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Sub "/${ProjectName}/DB_HOST"
      Type: "String"
      Value: !ImportValue DBEndpoint

  DBNameParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Sub "/${ProjectName}/DB_NAME"
      Type: "String"
      Value: !ImportValue DBName

  # SSM Parameter Store for DB Port (PostgreSQL default port)
  DBPortParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Sub "/${ProjectName}/DB_PORT"
      Type: "String"
      Value: "5432"
